// lib/handlers/lots.js — G3 product lot numbers.
// Routed via api/[...path].js as `case 'lots'` (no new serverless function).
// GET  ?lot_number=L00042              → single lot + product + destination (scan/lookup, powers G5 /scan)
// GET  ?collection_id=123              → lots generated by a collection (trace)
// GET  ?sku=2609&workorder_items_id=?  → In-Stock lots for a SKU (+ the one already on this item) — WO dropdown
// POST/PATCH ?action=assign|unassign|serial (body: lot_id, workorder_items_id?, serial_number?)
import { getClientWithTimezone } from '../db.js';

function methodNotAllowed(res, allowed) {
  res.setHeader('Allow', allowed.join(', '));
  return res.status(405).json({ error: 'Method not allowed' });
}

export default async function handler(req, res) {
  const client = await getClientWithTimezone();
  try {
    const { method, query, body } = req;

    if (method === 'GET') {
      if (query.lot_number) {
        // Safe field set only (no unit_cost / created_by) — this endpoint powers
        // the PUBLIC /scan lookup, so it must not leak our cost or any customer data.
        const r = await client.query(
          `SELECT pl.lot_id, pl.lot_number, pl.product_sku, pl.status, pl.serial_number,
                  pl.collection_id, pl.workorder_items_id,
                  p.name AS product_name, p.price AS product_price, p.stock AS product_stock,
                  wi.workorder_id, w.invoice_id
             FROM product_lots pl
             LEFT JOIN product p ON p.sku = pl.product_sku
             LEFT JOIN workorder_items wi ON wi.workorder_items_id = pl.workorder_items_id
             LEFT JOIN workorder w ON w.workorder_id = wi.workorder_id
            WHERE pl.lot_number = $1`,
          [String(query.lot_number).trim().toUpperCase()]
        );
        if (!r.rows.length) return res.status(404).json({ error: 'Lot not found' });
        return res.status(200).json(r.rows[0]);
      }

      if (query.collection_id) {
        const r = await client.query(
          `SELECT pl.*, p.name AS product_name, wi.workorder_id, w.invoice_id
             FROM product_lots pl
             LEFT JOIN product p ON p.sku = pl.product_sku
             LEFT JOIN workorder_items wi ON wi.workorder_items_id = pl.workorder_items_id
             LEFT JOIN workorder w ON w.workorder_id = wi.workorder_id
            WHERE pl.collection_id = $1
            ORDER BY pl.lot_number`,
          [query.collection_id]
        );
        return res.status(200).json(r.rows);
      }

      if (query.sku) {
        const sku = String(query.sku).trim().toUpperCase();
        const wiId = query.workorder_items_id ? Number(query.workorder_items_id) : null;
        const r = await client.query(
          `SELECT lot_id, lot_number, product_sku, status, serial_number, workorder_items_id
             FROM product_lots
            WHERE UPPER(product_sku) = $1
              AND (status = 'In Stock' OR ($2::int IS NOT NULL AND workorder_items_id = $2::int))
            ORDER BY lot_number`,
          [sku, wiId]
        );
        return res.status(200).json(r.rows);
      }

      return res.status(400).json({ error: 'Provide lot_number, collection_id, or sku' });
    }

    if (method === 'PATCH' || method === 'POST') {
      const action = query.action || body?.action;

      if (action === 'assign') {
        const lotId = Number(body?.lot_id);
        const wiId = Number(body?.workorder_items_id);
        if (!lotId || !wiId) return res.status(400).json({ error: 'lot_id and workorder_items_id required' });
        await client.query('BEGIN');
        try {
          // SKU must match between the lot and the workorder item (wrong-model guard, reused by the G5 scanner).
          const chk = await client.query(
            `SELECT pl.product_sku AS lot_sku, pl.status AS lot_status, wi.product_id AS wi_sku
               FROM product_lots pl
               JOIN workorder_items wi ON wi.workorder_items_id = $2
              WHERE pl.lot_id = $1
              FOR UPDATE OF pl`,
            [lotId, wiId]
          );
          if (!chk.rows.length) { await client.query('ROLLBACK'); return res.status(404).json({ error: 'Lot or item not found' }); }
          const row = chk.rows[0];
          if (String(row.lot_sku).toUpperCase() !== String(row.wi_sku).toUpperCase()) {
            await client.query('ROLLBACK');
            return res.status(409).json({ error: 'WRONG_MODEL', lot_sku: row.lot_sku, item_sku: row.wi_sku });
          }
          if (row.lot_status !== 'In Stock' && row.lot_status !== 'Assigned') {
            await client.query('ROLLBACK');
            return res.status(409).json({ error: `Lot is ${row.lot_status}` });
          }
          await client.query(
            `UPDATE product_lots SET status='Assigned', workorder_items_id=$1, updated_at=NOW() WHERE lot_id=$2`,
            [wiId, lotId]
          );
          await client.query('COMMIT');
          return res.status(200).json({ success: true });
        } catch (e) { try { await client.query('ROLLBACK'); } catch {} throw e; }
      }

      if (action === 'unassign') {
        const lotId = Number(body?.lot_id);
        if (!lotId) return res.status(400).json({ error: 'lot_id required' });
        await client.query(
          `UPDATE product_lots SET status='In Stock', workorder_items_id=NULL, updated_at=NOW()
            WHERE lot_id=$1 AND status='Assigned'`,
          [lotId]
        );
        return res.status(200).json({ success: true });
      }

      if (action === 'serial') {
        const lotId = Number(body?.lot_id);
        if (!lotId) return res.status(400).json({ error: 'lot_id required' });
        const sn = body?.serial_number == null ? null : (String(body.serial_number).trim() || null);
        await client.query(
          `UPDATE product_lots SET serial_number=$1, updated_at=NOW() WHERE lot_id=$2`,
          [sn, lotId]
        );
        return res.status(200).json({ success: true });
      }

      return res.status(400).json({ error: 'Unknown action' });
    }

    return methodNotAllowed(res, ['GET', 'POST', 'PATCH']);
  } catch (err) {
    console.error('lots handler error:', err);
    return res.status(500).json({ error: 'Server error' });
  } finally {
    client.release();
  }
}
